### ISSUE TITLE
Could not parse duration [undefined]

### ISSUE THREAD

**Issue by odscjames** [openactive/conformance-services#109]
```
Could not parse duration [undefined]
Therefore guessing repeat frequency from byDay..
Error generating schedule
TypeError: Cannot read property 'n' of undefined
    at parseOptions (/home/app/node_modules/rrule/dist/es5/rrule.js:1051:23)
    at new RRule (/home/app/node_modules/rrule/dist/es5/rrule.js:2125:29)
    at file:///home/app/src/lib/pipes/normalise-schedule-pipe.js:77:34
    at new Promise (<anonymous>)
    at NormaliseSchedulePipe.run (file:///home/app/src/lib/pipes/normalise-schedule-pipe.js:13:12)
    at file:///home/app/src/lib/pipeline.js:15:48
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
{
  type: 'PartialSchedule',
  byDay: [ 'http://schema.org/Friday' ],
  endTime: '10:00',
  duration: 'PT1H',
  startDate: '2020-07-31',
  startTime: '09:00',
  'beta:timeZone': 'Europe/London'
}
```

**Comment by rhiaro** [comment]
this is because they use `http://schema.org/..` instead of `https://schema.org/..` of course
